version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: banking_app
    ports:
      - "3000:3000"
    environment:
      - RAILS_ENV=development
    command: "bundle exec rails s -b 0.0.0.0"
    volumes:
      - .:/app